// menu
export const CHANGE_MENU_SELECTED = 'CHANGE_MENU_SELECTED'

// found
export const CHANGE_TABS_SELECTED = 'CHANGE_TABS_SELECTED'
export const CHANGE_CAROUSEE_SELECTED = 'CHANGE_CAROUSEE_SELECTED'
// export const CHANGE_CAROUSEE_SELECTED = 'CHANGE_CAROUSEE_SELECTED'

// footer
export const SET_CURRENT_SONG = 'SET_CURRENT_SONG'
export const SET_TIME_PROGREDSS = 'SET_TIME_PROGREDSS'
export const MUSIC_CONTROL = 'MUSIC_CONTROL'
export const SET_CURNT_POS = 'SET_CURNT_POS'
export const SET_POINT_POS = 'SET_POINT_POS'

// export const ADD_TO_CART = 'ADD_TO_CART'
// export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
// export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
// export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'
// export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'