// menu
export const CHANGE_MENU_SELECTED = 'CHANGE_MENU_SELECTED'

// found
export const CHANGE_TABS_SELECTED = 'CHANGE_TABS_SELECTED'
export const CHANGE_CAROUSEE_SELECTED = 'CHANGE_CAROUSEE_SELECTED'
// export const CHANGE_CAROUSEE_SELECTED = 'CHANGE_CAROUSEE_SELECTED'

// footer
export const SET_CURRENT_SONG = 'SET_CURRENT_SONG'

// export const ADD_TO_CART = 'ADD_TO_CART'
// export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
// export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
// export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'
// export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'